# Define the goal
Header header
-------
# Define the result
geometry_msgs/Pose[] path
std_msgs/Duration sampling_time
std_msgs/Duration gain_time
std_msgs/Duration collision_check_time
-------
# Define a feedback message
